language: node_js
node_js:
- node
deploy:
  provider: npm
  email: barlockm@gmail.com
  api_key:
    secure: bE52sXA2VRivX/S+5DB6EPZEZplUVaei1Ai+MDa21J4ytBAdYFgGrj0dI1wYvg2iZEmbHRz5gnzO/SQ7/EG3tDjCyRbvYHyKYae1xk5Nlbjh/0A6ECZnXlfeBEJ2fuLAnrfA9E5d+HBkDcn21giuhE3a456L69h5ejKR+9zGRdBBmnoD+zn/Lp4P87erq1r24H7+phzWK1c5vKgG6K0XFGW8bB5KRk0pGAI7v4UvOTqFzUK4pXUeYvWN9xfx0ZiNVW2oFZtU0K8dk82nM7s/qb6y2+9Re4EteFR2EYiyiB6S+UqhDxbNEOx7UnpycApzpUvzeVwFObCw4APPiQ1yCX6qjLQ5IoOolrqtg4uPsGxAEkGtTfuqAC9Mv+orfvnQ9zxkOxyXZvEn1eGKxAD2Bq8fOVbzSp8S4A1BMnrgIurN6M2WLuJxQl7LezgQZQ8lvizjGLmbHLPUQ3u6YwCyJmhQPJz4n1fdLd45JcWvpnKjK9fL85FbAUWPZ5z+U42mq0B5mbiwpDUfItJfk9LpyGWG1xvz+XKwPLWUfuZ0hWpR4NPuF8WO87EgQS7L9HD5eaS9QlCPgLFHoPMZmSNIYKeikV04qpc3UgrNbG/mv5sZyOFgaYAevWoI69yCdOigkvgmlLnpQsuQAEhuf5AKG6yyQElDj/GfEoVaHGGnYws=
  on:
    tags: true
    branch: master
